# Generated by Django 2.2 on 2022-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20220728_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.TextField(max_length=120),
        ),
    ]
